development:
  default:
    :url: "redis://localhost:6379/1"
  sidekiq:
    :url: "redis://localhost:6379/1"

test:
  default:
    :url: "redis://localhost:6379/1"
  sidekiq:
    :url: "redis://localhost:6379/1"

staging:
  default:
    :url: "redis://redis-staging:6379/1"
  sidekiq:
    :url: "redis://redis-staging:6379/1"

production:
  default:
    :url: "redis://redis-cache/1"
    :name: redis-cache
    :db: 1
    :sentinels:
      - :host: redis-prod-1
        :port: 26379
      - :host: redis-prod-2
        :port: 26379
      - :host: redis-prod-3
        :port: 26379
  sidekiq:
    :url: "redis://redis-sidekiq/1"
    :name: redis-sidekiq
    :db: 1
    :sentinels:
      - :host: redis-prod-1
        :port: 26379
      - :host: redis-prod-2
        :port: 26379
      - :host: redis-prod-3
        :port: 26379
