source "https://rubygems.org"

ruby "3.0.0"

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 7.1.3"

# Use sqlite3 as the database for Active Record
gem "sqlite3", "~> 1.4"

# Use the Puma web server [https://github.com/puma/puma]
gem "puma", ">= 5.0"

# Build JSON APIs with ease [https://github.com/rails/jbuilder]
# gem "jbuilder"

# Use Redis adapter to run Action Cable in production
# gem "redis", ">= 4.0.1"

# Use Kredis to get higher-level data types in Redis [https://github.com/rails/kredis]
# gem "kredis"

# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
# gem "bcrypt", "~> 3.1.7"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[mswin mswin64 mingw x64_mingw jruby]

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false

# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
# gem "image_processing", "~> 1.2"

group :development, :test do
  gem "rspec-rails", "~> 6.1.4"
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem "byebug", platforms: %i[mri mingw x64_mingw]

  gem "parallel_tests"
  gem "rubocop", require: false
  gem "rubocop-rails", require: false
  gem "rubocop-standard", require: false
  gem "standard", require: false
  gem "faker"
end

group :development do
  gem "listen", "~> 3.3"
  gem "solargraph", require: false
  gem "spring"
  gem "yard"
end

group :test do
  gem "brakeman", "~> 5.4"
  gem "bundler-audit", "~> 0.9.1"
  gem "factory_bot_rails"
  gem "rspec-sidekiq"
  gem "shoulda-matchers"
  gem "simplecov", "~> 0.22.0", require: false
  gem "simplecov-formatter-badge", "~> 0.1.0", require: false
  gem "vcr"
  gem "webmock"
  gem "database_cleaner-active_record"  # For cleaning test database
  gem "timecop"
end

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin Ajax possible
gem "httparty"
gem "rack-cors"
# Background Jobs ecosystem
gem "active_model_serializers"
gem "hiredis", "~> 0.6.0"
gem "redis", "~> 4.6.0", require: ["redis", "redis/connection/hiredis"]
gem "sidekiq", "~> 7.1.4"
gem "sidekiq-failures"
gem "sidekiq-scheduler"
gem "sidekiq-status"
gem "sidekiq-unique-jobs", "~> 8.0.3"

gem "websocket-client-simple"

gem "rswag"
gem "rack-attack"
gem "request_store"

gem "kaminari"      # For pagination
gem "jsonapi-rails" # For JSON:API compliant responses
gem "jsonapi-serializer" # JSON:API serializer

gem "airbrake"
gem "bcrypt"